# Generated by Django 4.0 on 2024-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
