# Generated by Django 4.0 on 2024-11-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
    ]
